"""
Phase II-D v2: Macro correction with expanded training data.

v1 problem: only 293 training samples (cal period only) -> XGBoost underfits.
v2 fix: 2243 training samples (full 2016-2022 walk-forward residuals) + 21 macro features.

Uses:
  - results/training_residuals.json (generated by generate_training_residuals.py)
  - data/raw/macro_extended.parquet (from fetch_macro_extended.py)
  - data/raw/macro.parquet (original macro data)

Usage:
  python -m pipeline.macro_correction_v2
"""
import json
import logging
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import xgboost as xgb

warnings.filterwarnings("ignore")
logger = logging.getLogger(__name__)
if not logger.handlers:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")

ROOT = Path(__file__).parent.parent
RESULTS = ROOT / "results"

# Temporal split
CAL_START = "2023-07-01"
CAL_END = "2024-06-30"
TEST_START = "2024-07-01"
TEST_END = "2025-03-31"


def load_macro_data() -> pd.DataFrame:
    """Load and merge all macro data sources."""
    frames = []

    # Original macro
    p1 = ROOT / "data/raw/macro.parquet"
    if p1.exists():
        df1 = pd.read_parquet(p1)
        df1.index = pd.to_datetime(df1.index)
        frames.append(df1)
        logger.info("  Original macro: %d rows, %d cols", len(df1), len(df1.columns))

    # Extended macro
    p2 = ROOT / "data/raw/macro_extended.parquet"
    if p2.exists():
        df2 = pd.read_parquet(p2)
        df2.index = pd.to_datetime(df2.index)
        # Drop duplicates with original
        dup_cols = [c for c in df2.columns if c in (frames[0].columns if frames else [])]
        if dup_cols:
            df2 = df2.drop(columns=dup_cols)
        frames.append(df2)
        logger.info("  Extended macro: %d rows, %d cols", len(df2), len(df2.columns))

    if not frames:
        raise FileNotFoundError("No macro data found")

    merged = pd.concat(frames, axis=1).sort_index().ffill()
    logger.info("  Merged macro: %d rows, %d cols", len(merged), len(merged.columns))
    return merged


def load_training_residuals() -> dict:
    """Load pre-computed TimesFM residuals."""
    path = RESULTS / "training_residuals.json"
    if not path.exists():
        raise FileNotFoundError(
            f"Training residuals not found at {path}. "
            "Run: python experiments/generate_training_residuals.py"
        )
    data = json.loads(path.read_text())
    logger.info("  Train residuals: %d samples", data["metadata"]["n_train"])
    logger.info("  Cal residuals: %d samples", data["metadata"]["n_cal"])
    return data


def prepare_features(residuals: list[dict], macro_df: pd.DataFrame,
                      btc_returns: pd.Series = None) -> tuple[np.ndarray, np.ndarray, list[str]]:
    """Build feature matrix from residuals + macro data.

    Features per sample:
      - TimesFM quantiles: q10, q50, q90, IQR (4)
      - IQR percentile rank in 60-day window (1)
      - Macro indicators z-scored with 30-day rolling window (~15-20)
      - BTC 30-day realized vol (1)

    Returns:
      X: feature matrix [n_samples, n_features]
      y: target (residual = actual - q10)
      feature_names: list of feature names
    """
    # Macro features to use (select available columns)
    macro_candidates = [
        "sp500", "nasdaq", "gold", "crude_oil", "dxy", "treasury_10y", "vix", "m2",
        # Extended
        "vix_yf", "move_index", "treasury_3m_yf", "russell_2000", "silver", "dxy_yf",
        "fear_greed", "btc_mcap_proxy",
        # Derived
        "yield_curve_10y3m", "vix_change_5d", "vix_change_20d",
        "sp500_return_5d", "sp500_return_20d", "sp500_vol_20d",
        "gold_btc_ratio", "dxy_change_5d",
    ]
    available_macro = [c for c in macro_candidates if c in macro_df.columns]
    logger.info("  Available macro features: %d / %d", len(available_macro), len(macro_candidates))

    # Z-score macro features with 30-day rolling window
    macro_z = pd.DataFrame(index=macro_df.index)
    for col in available_macro:
        roll_mean = macro_df[col].rolling(30, min_periods=5).mean()
        roll_std = macro_df[col].rolling(30, min_periods=5).std().clip(lower=1e-8)
        macro_z[f"{col}_z"] = (macro_df[col] - roll_mean) / roll_std

    # Build feature rows
    X_rows = []
    y_rows = []
    iqr_history = []

    for r in residuals:
        date = pd.Timestamp(r["date"])

        # TimesFM quantile features
        q10 = r.get("q10", 0)
        q50 = r.get("q50", 0)
        q90 = r.get("q90", 0)
        iqr = q90 - q10

        # IQR rank
        iqr_history.append(iqr)
        if len(iqr_history) > 60:
            iqr_history = iqr_history[-60:]
        iqr_rank = sum(1 for v in iqr_history if v <= iqr) / max(len(iqr_history), 1)

        # Macro features for this date (use nearest available date)
        macro_row = []
        if date in macro_z.index:
            macro_vals = macro_z.loc[date].values
        else:
            # Find nearest date
            idx = macro_z.index.searchsorted(date)
            if idx > 0:
                macro_vals = macro_z.iloc[idx - 1].values
            else:
                macro_vals = np.zeros(len(macro_z.columns))
        macro_row = list(np.nan_to_num(macro_vals, 0))

        # BTC realized vol (from the residuals themselves)
        recent_actuals = [rr["actual"] for rr in residuals[max(0, residuals.index(r)-30):residuals.index(r)]]
        btc_vol = np.std(recent_actuals) if len(recent_actuals) > 5 else 0

        # Combine features
        features = [q10, q50, q90, iqr, iqr_rank, btc_vol] + macro_row

        X_rows.append(features)
        y_rows.append(r["actual"] - q10)  # residual: actual - P10

    feature_names = ["q10", "q50", "q90", "iqr", "iqr_rank", "btc_vol_30d"]
    feature_names += [f"{c}_z" for c in available_macro]

    X = np.array(X_rows, dtype=np.float32)
    y = np.array(y_rows, dtype=np.float32)

    # Replace any remaining NaN/inf
    X = np.nan_to_num(X, nan=0, posinf=0, neginf=0)
    y = np.nan_to_num(y, nan=0)

    return X, y, feature_names


def train_xgb_correction(X_train: np.ndarray, y_train: np.ndarray,
                           X_val: np.ndarray, y_val: np.ndarray,
                           target_quantile: float = 0.05) -> xgb.XGBRegressor:
    """Train XGBoost quantile regression model."""
    model = xgb.XGBRegressor(
        objective="reg:quantileerror",
        quantile_alpha=target_quantile,
        n_estimators=500,
        max_depth=5,
        learning_rate=0.03,
        subsample=0.8,
        colsample_bytree=0.7,
        min_child_weight=10,
        reg_alpha=0.1,
        reg_lambda=1.0,
        random_state=42,
        early_stopping_rounds=50,
    )

    model.fit(
        X_train, y_train,
        eval_set=[(X_val, y_val)],
        verbose=False,
    )

    logger.info("  Best iteration: %d / %d", model.best_iteration, 500)
    return model


def evaluate(residuals: list[dict], macro_df: pd.DataFrame,
              model: xgb.XGBRegressor, feature_names: list[str],
              conformal_correction: float = 0.6654) -> dict:
    """Evaluate macro correction vs conformal on test set."""
    X_test, y_test, _ = prepare_features(residuals, macro_df)

    # Predictions
    corrections = model.predict(X_test)

    # Breach rates
    actuals = np.array([r["actual"] for r in residuals])
    q10_raw = np.array([r.get("q10", 0) for r in residuals])

    raw_breaches = np.mean(actuals < q10_raw)
    conformal_var = q10_raw - conformal_correction
    conformal_breaches = np.mean(actuals < conformal_var)
    macro_var = q10_raw - corrections
    macro_breaches = np.mean(actuals < macro_var)

    results = {
        "n_test": len(residuals),
        "target_rate": 0.05,
        "raw_p10_breach": float(raw_breaches),
        "conformal_breach": float(conformal_breaches),
        "macro_corrected_breach": float(macro_breaches),
    }

    logger.info("  Raw P10 breach:       %.1f%% (target 10%%)", raw_breaches * 100)
    logger.info("  Conformal breach:     %.1f%% (target 5%%)", conformal_breaches * 100)
    logger.info("  Macro corrected:      %.1f%% (target 5%%)", macro_breaches * 100)

    return results


def main():
    logger.info("=" * 60)
    logger.info("Phase II-D v2: Macro Correction (expanded dataset)")
    logger.info("=" * 60)

    # Load data
    logger.info("\n--- Loading data ---")
    residual_data = load_training_residuals()
    macro_df = load_macro_data()

    train_residuals = residual_data["train"]
    cal_residuals = residual_data["cal"]

    # Load test residuals from Phase 0.5
    test_residuals = []
    p05_path = RESULTS / "phase05_forecasts.json"
    if p05_path.exists():
        p05 = json.loads(p05_path.read_text())
        test_residuals = p05.get("test", [])
        logger.info("  Test residuals (Phase 0.5): %d samples", len(test_residuals))

    # Prepare features
    logger.info("\n--- Preparing features ---")
    logger.info("Training set:")
    X_train, y_train, feature_names = prepare_features(train_residuals, macro_df)
    logger.info("  X_train: %s, y_train: %s", X_train.shape, y_train.shape)

    logger.info("Calibration set (validation):")
    X_cal, y_cal, _ = prepare_features(cal_residuals, macro_df)
    logger.info("  X_cal: %s, y_cal: %s", X_cal.shape, y_cal.shape)

    # Train model
    logger.info("\n--- Training XGBoost ---")
    model = train_xgb_correction(X_train, y_train, X_cal, y_cal, target_quantile=0.05)

    # Feature importance
    importances = dict(zip(feature_names, model.feature_importances_))
    sorted_imp = sorted(importances.items(), key=lambda x: -x[1])
    logger.info("\n  Top 10 features:")
    for name, imp in sorted_imp[:10]:
        logger.info("    %s: %.4f", name, imp)

    # Evaluate on calibration set
    logger.info("\n--- Calibration set evaluation ---")
    cal_eval = evaluate(cal_residuals, macro_df, model, feature_names)

    # Evaluate on test set
    test_eval = {}
    if test_residuals:
        logger.info("\n--- Test set evaluation ---")
        test_eval = evaluate(test_residuals, macro_df, model, feature_names)

    # Save results
    output = {
        "phase": "II-D_v2",
        "training": {
            "n_train": len(train_residuals),
            "n_val": len(cal_residuals),
            "n_features": len(feature_names),
            "feature_names": feature_names,
            "feature_importance": {k: round(float(v), 4) for k, v in sorted_imp},
            "best_iteration": model.best_iteration,
        },
        "cal_evaluation": cal_eval,
        "test_evaluation": test_eval,
    }

    out_path = RESULTS / "phase2d_macro_correction_v2.json"
    out_path.write_text(json.dumps(output, indent=2))
    logger.info("\nResults: %s", out_path)


if __name__ == "__main__":
    main()
